import { db } from '../../infra/db.js';
import { languages } from '../models/languagesModel.js';

export async function seedLanguages() {
  await db
    .insert(languages)
    .values([
      { name: 'Afrikaans', code: 'AF' },
      { name: 'Albanian', code: 'SQ' },
      { name: 'Amharic', code: 'AM' },
      { name: 'Arabic', code: 'AR' },
      { name: 'Armenian', code: 'HY' },
      { name: 'Azerbaijani', code: 'AZ' },
      { name: 'Basque', code: 'EU' },
      { name: 'Belarusian', code: 'BE' },
      { name: 'Bengali', code: 'BN' },
      { name: 'Bosnian', code: 'BS' },
      { name: 'Bulgarian', code: 'BG' },
      { name: 'Catalan', code: 'CA' },
      { name: 'Chinese', code: 'ZH' },
      { name: 'Croatian', code: 'HR' },
      { name: 'Czech', code: 'CS' },
      { name: 'Danish', code: 'DA' },
      { name: 'Dutch', code: 'NL' },
      { name: 'English', code: 'EN' },
      { name: 'Estonian', code: 'ET' },
      { name: 'Finnish', code: 'FI' },
      { name: 'French', code: 'FR' },
      { name: 'Georgian', code: 'KA' },
      { name: 'German', code: 'DE' },
      { name: 'Greek', code: 'EL' },
      { name: 'Gujarati', code: 'GU' },
      { name: 'Hebrew', code: 'HE' },
      { name: 'Hindi', code: 'HI' },
      { name: 'Hungarian', code: 'HU' },
      { name: 'Icelandic', code: 'IS' },
      { name: 'Indonesian', code: 'ID' },
      { name: 'Irish', code: 'GA' },
      { name: 'Italian', code: 'IT' },
      { name: 'Japanese', code: 'JA' },
      { name: 'Kannada', code: 'KN' },
      { name: 'Kazakh', code: 'KK' },
      { name: 'Korean', code: 'KO' },
      { name: 'Latvian', code: 'LV' },
      { name: 'Lithuanian', code: 'LT' },
      { name: 'Macedonian', code: 'MK' },
      { name: 'Malay', code: 'MS' },
      { name: 'Malayalam', code: 'ML' },
      { name: 'Marathi', code: 'MR' },
      { name: 'Mongolian', code: 'MN' },
      { name: 'Nepali', code: 'NE' },
      { name: 'Norwegian', code: 'NO' },
      { name: 'Persian', code: 'FA' },
      { name: 'Polish', code: 'PL' },
      { name: 'Portuguese', code: 'PT' },
      { name: 'Punjabi', code: 'PA' },
      { name: 'Romanian', code: 'RO' },
      { name: 'Russian', code: 'RU' },
      { name: 'Serbian', code: 'SR' },
      { name: 'Slovak', code: 'SK' },
      { name: 'Slovenian', code: 'SL' },
      { name: 'Spanish', code: 'ES' },
      { name: 'Swahili', code: 'SW' },
      { name: 'Swedish', code: 'SV' },
      { name: 'Tamil', code: 'TA' },
      { name: 'Telugu', code: 'TE' },
      { name: 'Thai', code: 'TH' },
      { name: 'Turkish', code: 'TR' },
      { name: 'Ukrainian', code: 'UK' },
      { name: 'Urdu', code: 'UR' },
      { name: 'Vietnamese', code: 'VI' },
      { name: 'Welsh', code: 'CY' },
    ])
    .onConflictDoNothing();
}
